package com.cyber.portal.sharedResources.enums;

public enum IncidentStatus {
    SUBMITTED, RECEIVED, EVIDENCE_VERIFIED, ASSIGNED_TO_POLICE, UNDER_VERIFICATION, FIR_GENERATED, INVESTIGATING, RESOLVED, CLOSED
}
